[package]
name = "eos-rs-proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1" }
quote = { version = "1" }
syn = { version = "1" }
eos-rs-patches-def = { path = "../patches-def" }
